### ISSUE TITLE
working html example

### ISSUE THREAD

**Issue by dr-okra** [gl-transitions/gl-transitions#128]
Hi, can a simple index.html example be made to show how this can be used for a web page please? Maybe a jsfiddle or codepen? I and I'm sure others (starting out with shaders) would love to know how this can be made into an image slideshow, for example. Looking through the code of the examples, it doesn't seem accessible.

Thanks for this wonderful resource. I can't wait to start using it :)

**Comment by arinkverma** [comment]
Even I am also looking for Pure HTML or React working example. All documents seem insufficient.

**Comment by lucacattide** [comment]
I'm stuck too, just tried to run [this one](https://www.npmjs.com/package/gl-transition), with no success.

**Comment by gre** [comment]
appropriate repo is https://github.com/gre/gl-transition-libs/tree/master/packages . any help on updating these lib is welcomed, the present repository is still relevant and i believe not outdated

**Comment by angular-v** [comment]
Hi, can a simple index.html example be made to show how this can be used for a web page please? Maybe a jsfiddle or codepen? I and I'm sure others (starting out with shaders) would love to know how this can be made into an image slideshow, for example. Looking through the code of the examples, it doesn't seem accessible.

Thanks for this wonderful resource. I can't wait to start using it :)
