### ISSUE TITLE
Preview of a transition as a gif

### ISSUE THREAD

**Issue by mavrovgeorgi** [gl-transitions/gl-transitions#130]
Hello,

I would like to thank you for your awesome work. I would like to use some of the transitions in my website, but I didn't find any way to represent a transition as a gif for example, so the user could see a preview of it, how the transition looks like.

P.S: Previews, like the ones shown in the repository here.

Thank you!

**Comment by gre** [comment]
tools are in https://github.com/gre/gl-transition-libs/tree/master/packages
