### ISSUE TITLE
Transition between two image with different resolution

### ISSUE THREAD

**Issue by CreateChance** [gl-transitions/gl-transitions#131]
Hi @gre , your transitions look great! I want to add transition between two images with different resolution, how to make them look good and keep aspect ratio?

**Comment by CreateChance** [comment]
Thx, I'll try it.

**Comment by CreateChance** [comment]
Hi! I've imported all transitions to my project for now, my project [https://github.com/CreateChance/ImageEditor](url)  . It's an image editor on android platform, you can import many photo to it and then encode them to mp4 file with mediacodec and opengl es. Transition between images is your beautiful transitions! :) For now, the apk language is chinese, I'll translate them to english later.

**Comment by gre** [comment]
我会看一点儿中文！

**Comment by gre** [comment]
ok so what you can typically do is in these functions:

https://github.com/CreateChance/ImageEditor/blob/b5f0e25620b4e122cd48f27f49b37c5fedf20e60/imageeditor/src/main/assets/transitions/TransitionMainFragmentShader.glsl#L21-L27

you can change it to another implementation that would preserve the ratio. e.g. a zoomed crop (cover):


```glsl
vec4 getFromColor(vec2 uv){
  return texture2D(from,.5+(uv-.5)*vec2(min(ratio/_fromR,1.),min(_fromR/ratio,1.)));
}
vec4 getToColor(vec2 uv){
  return texture2D(to,.5+(uv-.5)*vec2(min(ratio/_toR,1.),min(_toR/ratio,1.)));
}
```

**Comment by gre** [comment]
where 

```js
      shader.uniforms._fromR = from.shape[0] / from.shape[1]; // (width / height)
      shader.uniforms._toR = to.shape[0] / to.shape[1]; // (width / height)
```

as in https://github.com/gre/gl-transition-libs/blob/master/packages/gl-transition/src/index.js#L69-L70

**Comment by CreateChance** [comment]
It works! Thanks man!

**Comment by gre** [comment]
Impressive stuff you are working on

**Comment by dumihi** [comment]
Hello, @CreateChance did this sample very well. I am using his gl transition for my project. But it has been for a long time for waiting his support. So please help me with his sample
I succeeded in setting transition for 2 image. Now i want to apply effect for each image and my transition also display their effect.
How can i do it? please help me. Thank you

**Comment by dumihi** [comment]
Hi I want to do transition keeping root 2 images, even second image has size less than first image
