### ISSUE TITLE
Repository Abandoned?

### ISSUE THREAD

**Issue by ReactGirl** [gl-transitions/gl-transitions#132]
Tried to have one example working with React but seems to be impossible with the current documentation.

**Comment by gre** [comment]
this repository is not abandoned and is technology agnostic. there are example implementations in context of: C/C++, Java, Node.js web, React Native, running this.

The web React one you are using is probably react-gl-transaction pkg? it's maintained in another repo https://github.com/gre/gl-transition-libs/tree/master/packages . if it's broken, PRs are accepted / or more help & investigation on what's broken is welcomed.
