### ISSUE TITLE
Simpler uniform initialisation syntax

### ISSUE THREAD

**Issue by jacereda** [gl-transitions/gl-transitions#133]
Hi,

Nice project. Would you consider a PR changing the shaders and the docs so that only the first variant of the uniform values initialisation is supported?

I want to use these from desktop OpenGL but I don't want to complicate the parsing more than needed.

**Comment by gre** [comment]
I'm not sure to understand what you are asking. do you have an example?

**Comment by jacereda** [comment]
PR: https://github.com/gl-transitions/gl-transitions/pull/140

Basically I want to make parsing easier by setting all initial values via `//` comments.

**Comment by gre** [comment]
Ok thanks. Merged
