### ISSUE TITLE
Is there any way to use these transitions in Android 

### ISSUE THREAD

**Issue by mansiJspaceo** [gl-transitions/gl-transitions#139]
Any way to use this Transition in Android

**Comment by gre** [comment]
Using OpenGL in Android should be possible, there is just no "vanilla" example of that yet

**Comment by dumihi** [comment]
good android example https://github.com/CreateChance/ImageEditor
@mansiJspaceo

**Comment by mansiJspaceo** [comment]
Thank you

**Comment by mansiJspaceo** [comment]
How can we Merge 2 videos with one Video have Sound & another Video is silent there is no any audio file
please Provide FFMPEG command for this

**Comment by SmartAppsDevelopment** [comment]
https://github.com/wysaid/android-gpuimage-plus

https://github.com/cats-oss/android-gpuimage
 you can get help from these library
