### ISSUE TITLE
"displacementMap" image for transition

### ISSUE THREAD

**Issue by cimt** [gl-transitions/gl-transitions#147]
Hello,
I use this slideshow:  [https://github.com/yomotsu/gl-slideshow](https://github.com/yomotsu/gl-slideshow)

with this transition (**and it works**): [https://gl-transitions.com/editor/displacement](https://gl-transitions.com/editor/displacement)

**But how can I create my own "displacementMap" image for this transition**

like this:
`texture2D???: 'images/displacement-image.png'`

And where can i find examples of easing functions (e.g. easeInOutCubic).

My goal is a slideshow like this: [https://tympanus.net/Development/webGLImageTransitions/index6.html](https://tympanus.net/Development/webGLImageTransitions/index6.html)

I would be happy about any help

**Comment by chestnut111** [comment]
same question......

**Comment by cimt** [comment]
Yes I'm sorry. I needed it fast for a project!
But questions have not been answered here for a long time.
