### ISSUE TITLE
How to change "Time Speed" with gl-transitions scripts cli like in "GLTransitions are configurable"? 

### ISSUE THREAD

**Issue by zhangluustb** [gl-transitions/gl-transitions#156]
How can i change "Time Speed" with gl-transitions scripts cli like in "GLTransitions are configurable"?

**Comment by gre** [comment]
I'm not exactly sure which script you are talking about? There is nothing that stops anyone to control the speed is as a gl-transition defines a progress value that can move from 0.0 to 1.0.
