### ISSUE TITLE
How to use with canvas of `lottie-web`?

### ISSUE THREAD

**Issue by wxs77577** [gl-transitions/gl-transitions#193]
I'm using `lottie-web` to render several lottie json on a canvas, how to make `gl-transition` works with canvas?

**Comment by gre** [comment]
are they webgl canvas? not sure if lottie allows that.

**Comment by wxs77577** [comment]
no, it just `2d context canvas`, but I've worked it out: just create another `gl canvas` to render `gl-transition` and draw it back to `2d canvas`.
