### ISSUE TITLE
How to use gl-transitions in pixijs?

### ISSUE THREAD

**Issue by xeoshow** [gl-transitions/gl-transitions#216]
Hello,

Just would like to know how to integrate gl-transitions into pixijs?
I found in most of the transitions, it used getFromColor and getToColor methods, but just could not find where are the two methods defined.
Could you please kindly help? Thanks a lot.

**Comment by benoitlahoz** [comment]
You have to define your own, for example : 

````glsl
vec4 getFromColor(vec2 uv) {
  return texture2D(from, uv);
}

vec4 getToColor(vec2 uv) {
  return texture2D(to, uv);
}
````
