### ISSUE TITLE
Need help for a new transition

### ISSUE THREAD

**Issue by Tonydepoule** [gl-transitions/gl-transitions#224]
Hello,
I am new here and I am looking to create a "Flip" transition.
I apologize in advance if I am not posting in the right place.
For now I have managed to create the zoom out, then the rotation and the zoom in.
But I would like to add a perspective effect during the rotation as in the image below.
Unfortunately my beginner knowledge is not sufficient.
If someone could help me a little, I would be very grateful.

![Capture du 2024-08-09 à 19 07 03](https://github.com/user-attachments/assets/1103d8ec-0079-4bc3-93e2-511c8abfbd22)

Here is my current code.

`
// Author: Anthony
// License: MIT
uniform vec4 color; // = vec4(0.0, 0.0, 0.0, 1.0);
vec4 transition (vec2 uv) {
  if (progress < 0.2) {
    float x = 0.5 + (uv.x-0.5) / (1.0-progress);
    float y = 0.5 + (uv.y-0.5) / (1.0-progress);
    if (x < 0.0 || x > 1.0 || y < 0.0 || y > 1.0) {
      return color;
    }
    else {
      vec2 fp = vec2(x, y);
      return getFromColor(fp);
    }
  }
  if (progress >= 0.2 && progress < 0.5) {
    float x = 0.5 + (uv.x-0.5) / ( 1.33 - 2.63 * progress);
    float y = 0.5 + (uv.y-0.5) / (0.8);
    if (x < 0.0 || x > 1.0 || y < 0.0 || y > 1.0) {
      return color;
    }
    else {
      vec2 fp = vec2(x, y);
      return getFromColor(fp);
    }
  }
  if (progress >= 0.5 && progress < 0.8) {
    float x = 0.5 + (uv.x-0.5) / (2.63 * progress - 1.33);
    float y = 0.5 + (uv.y-0.5) / (0.8);
    if (x < 0.0 || x > 1.0 || y < 0.0 || y > 1.0) {
      return color;
    }
    else {
      vec2 fp = vec2(x, y);
      return getToColor(fp);
    }
  }
  if (progress >= 0.8) {
    float x = 0.5 + (uv.x-0.5) / (progress);
    float y = 0.5 + (uv.y-0.5) / (progress);
    if (x < 0.0 || x > 1.0 || y < 0.0 || y > 1.0) {
      return color;
    }
    else {
      vec2 fp = vec2(x, y);
      return getToColor(fp);
    }
  }
}
`

**Comment by liubailin2017** [comment]
// Author: lbl 
// License: MIT 
uniform vec4 color; // = vec4(0.0, 0.0, 0.0, 1.0); 
float n = .3;
vec4 transition (vec2 uv) {
    if (progress < 0.2) {
        float x = 0.5 + (uv.x-0.5) / (1.0-progress); float y = 0.5 + (uv.y-0.5) / (1.0-progress); 
        if (x < 0.0 || x > 1.0 || y < 0.0 || y > 1.0) {
            return color; 
    } else {
                vec2 fp = vec2(x, y);
                return getFromColor(fp); 
            } 
    } 
    if (progress >= 0.2 && progress < 0.5) { 
        vec2 uv = 2. * vec2((uv.x-0.5) /( 0.8),(uv.y-0.5) / (0.8));
        
        float t = (progress - .2) / .3; // 0 ~ 1.
        uv.x = uv.x / (1. - t );
        uv.y = uv.y / ( 1. + t * n * uv.x);
        if (uv.x < -1. || uv.x > 1.0 || uv.y < -1.0 || uv.y > 1.0) { 
            return color; 
        }
        else {
            return getFromColor( vec2(.5)  + uv * .5); 
        }
    }

    if (progress >= 0.5 && progress < 0.8) {
        vec2 uv = 2. * vec2((uv.x-0.5) /( 0.8),(uv.y-0.5) / (0.8));
        
        float t = (progress - .5) / .3; // 0 ~ 1.
        uv.x = uv.x / ( t );
        uv.y = uv.y / ( 1. +   (1. - t) * n * (  - uv.x));
        if (uv.x < -1. || uv.x > 1.0 || uv.y < -1.0 || uv.y > 1.0) { 
            return color; 
        }
        else {
            return getToColor( vec2(.5)  + uv * .5); 
        }
    }
    if (progress >= 0.8) {
        float x = 0.5 + (uv.x-0.5) / (progress); 
        float y = 0.5 + (uv.y-0.5) / (progress); 
        if (x < 0.0 || x > 1.0 || y < 0.0 || y > 1.0) {
                return color;
        } else {
                vec2 fp = vec2(x, y); 
            return getToColor(fp); 
        } 
    }
}


//This is an approximate effect

**Comment by Tonydepoule** [comment]
Thank you very much @liubailin2017, this is exactly what I was looking to do.
