### ISSUE TITLE
paniq's transition

### ISSUE THREAD

**Issue by gre** [gl-transitions/gl-transitions#41]
Hi @paniq, how are you?

A few years ago, I was running GLSL.io but recently shut it down to focus on various OSS libraries, now I'm back on this GL Transition concept 🙂 I am rebooting GL Transitions.

Next week, I'll release this webapp: https://gl-transitions.netlify.com/ that is a fresh reboot of the previous transitions.glsl.io .

As you were the creator of some transitions, I wanted to ping you once before going full public 😅

You have created in the past this transition:

- https://gist.github.com/paniq/5a4d1fb6711076d17e2e

**Would you mind porting them in?** You basically need to paste them into https://gl-transitions.netlify.com/editor and click on "Publish on Github" (you might need to add a name, author name and polish some code if you want).

Then you can create a Pull Request on Github, it will gets to the website gallery when we merge it! (using some Travis, NPM) That's all, no server, all web services ;)

Hope you enjoy this new version and feel free to report any things for me to improve!
I dedicate my next days in polishing this release.

Thanks!

**Comment by paniq** [comment]
hi gre,

sorry i'm just seeing this now. i hereby release the code to the public domain, please do with it as you like

**Comment by gre** [comment]
ok! I just created this PR https://github.com/gl-transitions/gl-transitions/pull/98 (the import script makes everything easy to do that ;) ) – feel free to play on the new gl-transitions.com and thx for that shader :)

see on that PR, everything is green and the validation bot generated this nice GIF 😉  ![](https://camo.githubusercontent.com/adb9ed16ef43681cb03be764692ab0c09018ca2f/687474703a2f2f692e696d6775722e636f6d2f684b496b337a532e676966)
