### ISSUE TITLE
P-Seebauer's transition

### ISSUE THREAD

**Issue by gre** [gl-transitions/gl-transitions#44]
Hi @P-Seebauer, how are you?

A few years ago, I was running GLSL.io but recently shut it down to focus on various OSS libraries, now I'm back on this GL Transition concept 🙂 I am rebooting GL Transitions.

Next week, I'll release this webapp: https://gl-transitions.netlify.com/ that is a fresh reboot of the previous transitions.glsl.io .

As you were the creator of some transitions, I wanted to ping you once before going full public 😅

You have created in the past this transition:

- https://gist.github.com/P-Seebauer/597954724feda999b2cf2b5518d3edec

**Would you mind porting them in?** You basically need to paste them into https://gl-transitions.netlify.com/editor and click on "Publish on Github" (you might need to add a name, author name and polish some code if you want).

Then you can create a Pull Request on Github, it will gets to the website gallery when we merge it! (using some Travis, NPM) That's all, no server, all web services ;)

Hope you enjoy this new version and feel free to report any things for me to improve!
I dedicate my next days in polishing this release.

Thanks!

**Comment by P-Seebauer** [comment]
Hi. I was recently trying to show your site to a colleague and noticed it went down. So… great to hear that it's going up again. ☺

Work keeps me busy at the moment, but in one, two weeks I'll give it a try.

**Comment by gre** [comment]
ok, i ported it over in my series of "porting the old transition" :)  cheers!

https://github.com/gl-transitions/gl-transitions/pull/94
