### ISSUE TITLE
transitionify glsl-blend

### ISSUE THREAD

**Issue by Martin-Pitt** [gl-transitions/gl-transitions#95]
It would be awesome to see the blending modes from https://github.com/jamieowen/glsl-blend turned into realtime transitions.

`glsl-blend` features blending modes similar to what Adobe helpd push to the 2D Canvas drawing APIs in [`CanvasRenderingContext2D.globalCompositeOperation`](https://developer.mozilla.org/en-US/docs/Web/API/CanvasRenderingContext2D/globalCompositeOperation) and CSS's `background-blend-mode`.

Blend modes might need to be adjusted to be able to transition between images (e.g. opacity change towards the start/end and have mid point with the strongest blending effect).

**Comment by gre** [comment]
sounds a great idea! i guess one simple way is as you suggested to have a start/mid/end point thing, but I imagine there might be potential other cases where you could have blending configuration.
I'm probably not going to support glslify right now tho, so it will be per transition that you probably would have to hardcode these.
